sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends
      texlive-latex-recommended
      texlive-latex-extra
      texlive-fonts-recommended
      latex-xcolor
      texlive-lang-portuguese
script:
- latex    -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
- bibtex   CPC-NEURO2014
- pdflatex -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
