sudo: required
before_script:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends
      texlive-latex-recommended
      texlive-latex-extra
      texlive-fonts-recommended
      latex-xcolor
      texlive-lang-portuguese
- openssl aes-256-cbc -K $encrypted_6609dda7fdde_key -iv $encrypted_6609dda7fdde_iv -in publish-key.enc -out publish-key -d -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:fhcflx/cpc-neuro.git
- git fetch origin -f master:master
script:
- pdflatex -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
- bibtex   CPC-NEURO2014
- pdflatex -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
after_success:
- git add CPC-NEURO2014.pdf && git commit -m "pdf update" && git push origin HEAD:master
on:
  branch: master
