sudo: required
before_script:
- chmod a+x script/cibuild
- script/cibuild
script:
- pdflatex -interaction=nonstopmode -halt-on-error cpc-neuro2014/CPC-NEURO2014.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap4*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap5*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap2*.tex
- bibtex   cpc-neuro2014/CPC-NEURO2014
- bibtex cap1*
- bibtex cap2*
- bibtex cap3*
- bibtex cap4*
- bibtex cap5*
- bibtex ap1*
- bibtex ap2*
- pdflatex -interaction=nonstopmode -halt-on-error cpc-neuro2014/CPC-NEURO2014.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap4*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap5*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap2*.tex
after_success:
- chmod a+x script/afterbuild
- script/afterbuild
on:
  branch: master
