sudo: required
before_script:
- chmod a+x script/cibuild
- script/cibuild
script:
- pdflatex -interaction=nonstopmode -halt-on-error cpc-neuro2014/CPC-NEURO2014.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap4*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap5*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap4*.tex
- bibtex   cpc-neuro2014/CPC-NEURO2014
- bibtex cap1*.tex
- bibtex cap2*.tex
- bibtex cap3*.tex
- bibtex cap4*.tex
- bibtex cap5*.tex
- bibtex ap1*.tex
- bibtex ap2*.tex
- bibtex ap3*.tex
- bibtex ap4*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cpc-neuro2014/CPC-NEURO2014.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap4*.tex
- pdflatex -interaction=nonstopmode -halt-on-error cap5*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap1*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap2*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap3*.tex
- pdflatex -interaction=nonstopmode -halt-on-error ap4*.tex
after_success:
- chmod a+x script/afterbuild
- script/afterbuild
on:
  branch: master
