sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends
      texlive-latex-recommended
      texlive-latex-extra
      texlive-fonts-recommended
      latex-xcolor
      texlive-lang-portuguese
script:
- pdflatex -interaction=nonstopmode -halt-on-error v0.1/CPC-NEURO2014.tex
