sudo: required
before_script:
- chmod + script/cibuild
- script/cibuild
script:
- pdflatex -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
- bibtex   CPC-NEURO2014
- pdflatex -interaction=nonstopmode -halt-on-error CPC-NEURO2014.tex
after_success:
- chmod + script/afterbuild
- script/afterbuild
on:
  branch: master
