# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
exclude: [README.md,LICENSE.md,.bundle,.git,_site,Gemfile,Gemfile.lock,NO-HIAS,v0.1]
baseurl: "/cpc-neuro" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Francisco H. C. Felix"
# Build settings
markdown: kramdown
