#!/usr/bin/env bash
set -e # halt script on error

#sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
     texlive-latex-recommended \
     texlive-latex-extra \
     texlive-fonts-recommended \
     latex-xcolor \
     texlive-lang-portuguese \
     texlive-pictures \
     pgf 
      
openssl aes-256-cbc -K $encrypted_6609dda7fdde_key -iv $encrypted_6609dda7fdde_iv -in publish-key.enc -out publish-key -d -out ~/.ssh/publish-key -d
chmod u=rw,og= ~/.ssh/publish-key
echo "Host github.com" >> ~/.ssh/config
echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
git remote set-url origin git@github.com:fhcflx/cpc-neuro.git
git fetch origin -f master:master
cp cpc-neuro2014/bib.bib ./
